### ISSUE TITLE
Bug: Taskbar indicator -> show main 

### ISSUE THREAD

**Issue by sonvirgo** [Dragon2fly/vpngate-with-proxy#25]
```
Vpn command: Traceback (most recent call last):                                                       ↑↓ page: 1/6
  File "vpn_indicator.py", line 317, in change_focus                    
    call(['wmctrl', '-a', 'vpngate-with-proxy'])                        
  File "/usr/lib/python2.7/subprocess.py", line 168, in call            
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)leted 1
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exceptionpngate.net
OSError: [Errno 2] No such file or directory
```

No any process named vpngate-with-proxy
```
sudo ps -aux | grep vpn*
  8458  0.0  0.0  14372    28 pts/0    S    11:37   0:00 /bin/bash /home/virgosun/Documents/vpngate-with-proxy/run
root      8460  0.0  0.4 647504  9228 pts/0    Sl   11:37   0:12 python vpn_indicator.py
root     10247  0.0  0.1  60704  2644 pts/0    S+   19:22   0:00 sudo /home/virgosun/Documents/vpngate-with-proxy/run
root     10251  0.0  0.1  14372  2204 pts/0    S+   19:22   0:00 /bin/bash /home/virgosun/Documents/vpngate-with-proxy/run
root     10262  0.0  0.1  60704  2652 pts/0    S+   19:22   0:00 sudo python vpnproxy_tui.py /home/virgosun
root     10266  0.7  2.5 1118156 46744 pts/0   Sl+  19:22   0:01 python vpnproxy_tui.py /home/virgosun
```

**Comment by Dragon2fly** [comment]
Hi @sonvirgo 

It seems that you don't have `wmctrl` installed on your system. You may install it and try again.

    sudo apt install wmctrl

The `run` file has an 8-line ensured that `vpngate-with-proxy` appear in the terminal title bar. Then `wmctrl` will switch focus into the first window have that text.

**Comment by sonvirgo** [comment]
You are correct. Install wmctrl works
This is new issue although app run fine
```
Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

**Comment by Dragon2fly** [comment]
The new issue is not a problem as the program runs fine. Anyway, that issue is out of my hand too since it came from the gobject library.
